### PR TITLE
some updates

### PR DESCRIPTION
**Pull request by protonesso**
busybox 1.27.1 and linux-4.9.38

### CODE REVIEW

**Comment by ivandavidov** [comment]
You have error in the kernel link.

**Comment by protonesso** [comment]
ok, i rember

**Comment by protonesso** [comment]
fixed!

**Comment by ivandavidov** [comment]
And have you tested these changes or you just updated the configuration file and created PR?

**Comment by protonesso** [comment]
I have a problems with Makefile, it writes: "time: command not found", but maybe it works, create new branch called "experemental" for testing new software and ideas!

**Comment by ivandavidov** [comment]
Well, maybe you have to go through the project description and read carefully the instructions. You want to submit PR to an OS related project but you are not testing and building the PR changes at all. That's unacceptable!

I'll decline the PR because it hasn't been tested and I don't have the time to test it myself.

**Pull request closed without merging**
