### PR TITLE
fio bundle

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
I have tested with a full build and boot.

### CODE REVIEW

**Comment by ivandavidov** [comment]
In the future please make sure that you also try the functionality after you boot MLL. It doesn't make sense to add software in MLL which doesn't work after boot.

The ``fio`` functionality depends on 3 GLIBC libraries:

* lirdl
* librt
* libpthread

I have fixed the bundle.

**Comment by TechnologyClassroom** [comment]
Thank you!  I had tested this with glibc.

**Comment by ivandavidov** [comment]
There have been some major development changes recently and this is the reason why the necessary GLIBC libraries were missing. My apologies.

I have updated the bundle to reflect these changes but I haven't pushed them yet. You will see what I've changed after I push the changes.

**Comment by TechnologyClassroom** [comment]
Ok, sounds good!

To keep you in the loop, I will be busy at work for the next few months.  Everyone puts in orders at the end of the year.  My development time has disappeared.  I had to come up with a solution quick so I customized Arch with archiso.  My current Arch image is too heavily with systemd, but it will do for the moment.

I am still listening to all of the commits and I will pick up the project again once I have time.

**Comment by ivandavidov** [comment]
No worries, take care of your business. Your pull requests are highly appreciated and you are welcome to join the project again when you have time for it.

**Pull request merged**
