### PR TITLE
ncurses overlay

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
Some packages in util-linux such as dmesg depend on ncurses' libtinfo.so.5 library.  This pull request satisfies those dependencies.

I have tested this with the full iso build under Ubuntu 16.04.

### CODE REVIEW

**Comment by ivandavidov** [comment]
Thank you - this library is really useful in some situations!

**Comment by bauen1** [comment]
Please ensure your bundle scripts are marked as executable (`chmod +x`) in the future.

**Comment by bauen1** [comment]
Please ensure your bundle scripts are marked as executable (`chmod +x`) in the future.

**Comment by TechnologyClassroom** [comment]
@bauen1, the files are 775 on my machine.  I cloned the repo and they show as 664.  I am not sure how to fix this or what I could have done differently.

**Comment by ivandavidov** [comment]
In general I agree with @bauen1 that as a good practice all scripts should be pushed with ``+x``. I admit that in the past I myself have pushed some scripts as non-executable. :)

I intend to publish new MLL release in December and then I will check each script, so even if there are unresolved 'chmod' permission discrepancies, I will take care of them.

**Comment by TechnologyClassroom** [comment]
I will check my branch for this before the pull request of my next bundle.

**Pull request merged**
