### PR TITLE
glibc packages

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
Added glibc folder instead of only the libs as discussed in #100.

### CODE REVIEW

**Comment by ivandavidov** [comment]
Have you tested the ISO image size? How much MB does this add? I ask because I remember that the whole GLIBC build is really huge.

**Comment by ivandavidov** [comment]
Also, is the ``ldd`` binary available after you boot MLL?

**Comment by TechnologyClassroom** [comment]
I did not do this correctly.  I will close and resubmit once I fix it.  Since the entire package varies so greatly in size, I will separate into a separate bundle.

**Comment by ivandavidov** [comment]
Just a hint - MLL needs the ``so`` libraries. This has been handled already. In addition, it will be good to have the generated binaries (for now) and nothing more in order to keep the overall size as small as possible.

**Comment by bauen1** [comment]
Somewhat unrelated, the big mama hack fails on a i686 debian host https://github.com/ivandavidov/minimal/blob/master/src/minimal_overlay/bundles/mll_utils/03_installer.sh#L116

**Comment by ivandavidov** [comment]
You can delete the whole hack in order to fix the compilation process. or just ignore this whole bundle. It has been experimental for a long time.

**Comment by TechnologyClassroom** [comment]
Adding the entire $WORK_DIR/glibc/glibc_installed folder adds 38MiB to the ISO size and did not work in my test.  I am abandoning this branch concept.

**Comment by ivandavidov** [comment]
You cannot blindly add the whole folder. Right now I don't have GLIBC build in front of me but you might be overloading the dynamic loader with the one from the bundle and this might be causing you troubles. Or perhaps the bundle has ``ld.so.conf`` file which breaks the default Linux loader behavior. My point is that GLIBS is tricky piece of software.

I believe you would have success if you just add the executable binaries to the bundle, e.g. ``ldd`` and perhaps some others from the GLIBC build folder.

**Comment by TechnologyClassroom** [comment]
That makes sense.  I will try just moving the bin and lib folders once before moving on.

**Comment by TechnologyClassroom** [comment]
Same result as before.

/ # ldd
/bin/sh: ldd: not found
/ # ls /bin/ldd
/bin/ldd
/ # chmod 755 /bin/ldd
/ # /bin/ldd
/bin/sh: /bin/ldd: not found

I am going to just move on.  I can upload my work files on this if you would like to continue towards ldd.

**Comment by ivandavidov** [comment]
I debugged the issue. Note that the ``ldd`` binary is actually a shell script. I admit I didn't know that!

OK, in general here are some commands that really help when you have such issues:

* ``ldd </path/to/file>`` - shows the library dependencies.
* ``file </path/to/file>`` - shows the file type, including some additional useful information.

I also got to the point where ``/bin/ldd`` returned the message ``not found`` and then I applied the above commands on the ``ldd`` file located in ``/work/glibc/glibc_installed/bin/ldd``. I was really surprised to find out that ``ldd`` is a shell script!!!

At this point I opend the ``ldd`` script and found out that the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) was pointing to ``/bin/bash``. However, MLL only provides ``/bin/sh``. And since there is no 'bash' in MLL we end up with the not so useful error message 'not found'. I workarounded the issue by changing the ``ldd``'s shebang to point to ``/bin/sh`` (I manually edited the file) and after that it worked perfectly fine.

Note that in the folders ``bin`` and ``sbin`` under ``work/gibc/glibc_installed`` there are both ELF executable files and BASH shell script files. Thanks to your work and your efforts now I know that I have to be careful with the script files there.

If you'd like to try again, I suggest you add both the ``bin`` and ``sbin`` GLIBC directories, loop over the files in these directories one by one, detect the type for each file and if the file is shell scripts, then change the shebang to point to 'sh' instead of 'bash'. And if it is normal ELF binary, then simply reduce its size in the usual way.

I know it sounds complex but it is doable. The most complex part will be the file type detection but I'm sure you will figure out how to parse the output from the ``file`` command. I have already done something similar [here](https://github.com/ivandavidov/minimal/blob/5fd607b630269441874ab286633d54961dd65418/src/09_generate_rootfs.sh#L44).

Like I said before - GLIBC is tricky software piece.

I admit this was tricky issue!

**Comment by TechnologyClassroom** [comment]
Adding /bin/bash is one of my future plans.  Maybe we should just make bash a dependency of this.

**Comment by TechnologyClassroom** [comment]
Alternatively, I could replace /bin/bash with /bin/sh using sed.  It feels like a hack to me, but maybe worth a try.

**Comment by ivandavidov** [comment]
_Adding /bin/bash is one of my future plans. Maybe we should just make bash a dependency of this._

Or maybe we should think a little more before we suggest such things. :)

Have you researched the ``bash`` dependencies? It depends on GLIBC (what a surprise) and it also depends on ``readline`` which I think also depends on GLIBC . Adding bash as dependency of GLIBC makes circular dependency here.

GLIBC is the layer which communicates with the kernel. Other software may depend on GLIBC but definitely not the other way around. In this particular case if we want these scripts to work we should modify them to point to ``/bin/sh``.

**Comment by TechnologyClassroom** [comment]
I will test out the sed method today.

**Comment by TechnologyClassroom** [comment]
This simple substitution seems to work.  If my full build works, I will push shortly.

**Pull request closed without merging**
