### PR TITLE
Spelling Correction

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
I found a misspelled word.

### CODE REVIEW

**Comment by ivandavidov** [comment]
Nice catch - thanks!

**Comment by TechnologyClassroom** [comment]
You are welcome, Ivan!

Quick question!  I was able to use your scripts to build an ISO.  At which phase could I insert more compiled programs?  I want to add coreutils, util-linux, tmux, and a few others.

**Comment by ivandavidov** [comment]
Take a look at the ``minimal_overlay/bundles`` folder. That's the location where all additional software bundles are compiled and packaged.

If you'd like to add binary packages, then the easiest way would be to put all the stuff directly in the ``minimal_overlay/rootfs`` folder. Then all you need to do is to generate the ISO image once again.

**Comment by TechnologyClassroom** [comment]
Thank you!

**Pull request merged**
