### PR TITLE
catch up the bus

### PR DESCRIPTION
**Pull request by jyf007**
for slow network . i need mirrors to download file.

### CODE REVIEW

**Comment by jyf007** [comment]
but the project need checksum the source code.

**Comment by jyf007** [comment]
but the project need checksum the source code.

**Comment by K1773R** [comment]
- you want to use mirros, but only specify 1 source, instead of a source and multiple mirrors. -> thats not how mirrors should work... define a source and then linkts to the mirrors with a function that tries pulling from then until file found.
- you enable quite some overlays -> why?
- you source the files instead of grep/cut -> good.
- you change sh to bash -> mediumish, just so you can use source? (see above)
- you make a comment about using checksum -> good.
- you chane the paths for the overlays -> why?

this is quite a big change nested together.
if you want to get checksums implemented, create separate pull request for it (if you implement that).
if you want the sourcing of .config included, create a separate pull request only with this. but then it would be bash forcefully.

just some observations by looking over it.

**Comment by ivandavidov** [comment]
@jyf007 - I respect your efforts but I won't accept this pull request since it doesn't really add value to the project.

There are many ways to do the same thing in the Linux world and my way is what I do with MLL. I know that many people ``source`` the configuration file but I personally like my approach with ``grep + cut``. Also, you have enabled pretty much all overlay bundles. There is a reason for these bundles to be disabled by default - the build process becomes unstable and there is no guarantee that the bundles will be prepared correctly.

Last but not least, using ``Gentoo`` as _kind-of-mirror_ is not an option for me. I want the people to be able to see how the original sources are used from their original websites.

That said, I suggest you keep working on your MLL fork. Feel free to modify it as you see fit (it is you copy of MLL after all) and if you believe you have added something interesting, create another pull request where you include **only one** feature per pull request.

**Pull request closed without merging**
