### PR TITLE
update linux to 4.14.11 and busybox to 1.28.0

### PR DESCRIPTION
**Pull request by protonesso**
all updated packages are compiling and working good! as a proof image: https://imgur.com/a/DKlLx

### CODE REVIEW

**Comment by bauen1** [comment]
This Pull Request Fixes #111

**Comment by protonesso** [comment]
and we are need to wait for busybox 1.28.1?

**Comment by bauen1** [comment]
Not necessarily, but a release is scheduled for 28.1.18 and it _might_ be better to have stable versions in the release, as they have already been bug tested.

**Comment by ivandavidov** [comment]
@bauen1  - thank you for pointing out that BusyBox 1.28 is unstable.

@protonesso - in general it is OK to update the minor version of the Linux kernel since it is very unlikely to get into any kind of trouble as long as the kernel build is stable. However, for BusyBox it is better to use the latest released stable version which is ``1.27.2``.

Please update the PR to include only the kernel change (and also make sure that the build works, just in case) and I will merge it.

**Comment by ivandavidov** [comment]
@protonesso - please have in mind that Linux kernel 4.14.9 introduces new mandatory build dependency (issue #141) due to the following default configuration:

```
CONFIG_UNWINDER_ORC=y
```

You can check it here: https://lwn.net/Articles/742247/

This means that MLL cannot upgrade to newer kernel version by simply increasing the kernel patch number. I don't know how you have circumvented this dependency in your build. The proper way to ensure that everything works fine would be to use clean host machine with freshly installed OS. In that way you can easily detect the missing build dependencies.

**Pull request closed without merging**
